# Generated by Django 3.2 on 2021-05-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
